### ISSUE TITLE
Whitelist causes errors if not in node >= v0.5x

### ISSUE THREAD

**Issue by deremer** [aheckmann/gleak#3]
I deploy on Heroku so sadly, I'm stuck with 0.4x until they update.

I had to comment out line 97-108 in index.js to get the scrip to run.

Not a super huge deal, but thought you might like to know in case someone else has the same requirements.

This is awesome though, thank you for making it! I'm happy to say I only had 1!

**Comment by aheckmann** [comment]
hm, i just tested locally node v0.4.0 - v.0.4.12, the only version that failed was 0.4.0 and for a different reason than what you are describing here.

what error msg are you getting?
can you show me how to reproduce?

**Comment by deremer** [comment]
Sure, I'm running node v0.4.10 on a mac.

If I add this:

var gleak = require('gleak')();
gleak.print();

I get this uncaught exception:

ReferenceError: ArrayBuffer is not defined
    at Object.<anonymous> (/Users/dd/Developer/node-v0.4.10/node_modules/gleak/index.js:96:3)
    at Module._compile (module.js:423:26)
    at Object..js (module.js:429:10)
    at Module.load (module.js:339:31)
    at Function._load (module.js:298:12)
    at require (module.js:367:19)
    at Object.<anonymous> (/Users/dd/Developer/node-v0.4.10/projects/Paste/Paste-Web/app.js:224:13)
    at Module._compile (module.js:423:26)
    at Object..js (module.js:429:10)
    at Module.load (module.js:339:31)

If I comment out those lines in the whitelist it runs fine...

**Comment by deremer** [comment]
And for the record my Worker had 7. Oops!

**Comment by aheckmann** [comment]
weird. i must be parsing process.version incorrectly. what does
`process.version` say?

On Wed, Nov 23, 2011 at 9:48 AM, David DeRemer <
reply@reply.github.com

> wrote:
> 
> Sure, I'm running node v0.4.10 on a mac.
> 
> If I add this:
> 
> var gleak = require('gleak')();
> gleak.print();
> 
> I get this uncaught exception:
> 
> ReferenceError: ArrayBuffer is not defined
>    at Object.<anonymous>
> (/Users/dd/Developer/node-v0.4.10/node_modules/gleak/index.js:96:3)
>    at Module._compile (module.js:423:26)
>    at Object..js (module.js:429:10)
>    at Module.load (module.js:339:31)
>    at Function._load (module.js:298:12)
>    at require (module.js:367:19)
>    at Object.<anonymous>
> (/Users/dd/Developer/node-v0.4.10/projects/Paste/Paste-Web/app.js:224:13)
>    at Module._compile (module.js:423:26)
>    at Object..js (module.js:429:10)
>    at Module.load (module.js:339:31)
> 
> If I comment out those lines in the whitelist it runs fine...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aheckmann/gleak/issues/3#issuecomment-2849493

## 

Aaron

**Comment by aheckmann** [comment]
maybe theres space in at the beginning or smth?

On Wed, Nov 23, 2011 at 9:48 AM, David DeRemer <
reply@reply.github.com

> wrote:
> 
> Sure, I'm running node v0.4.10 on a mac.
> 
> If I add this:
> 
> var gleak = require('gleak')();
> gleak.print();
> 
> I get this uncaught exception:
> 
> ReferenceError: ArrayBuffer is not defined
>    at Object.<anonymous>
> (/Users/dd/Developer/node-v0.4.10/node_modules/gleak/index.js:96:3)
>    at Module._compile (module.js:423:26)
>    at Object..js (module.js:429:10)
>    at Module.load (module.js:339:31)
>    at Function._load (module.js:298:12)
>    at require (module.js:367:19)
>    at Object.<anonymous>
> (/Users/dd/Developer/node-v0.4.10/projects/Paste/Paste-Web/app.js:224:13)
>    at Module._compile (module.js:423:26)
>    at Object..js (module.js:429:10)
>    at Module.load (module.js:339:31)
> 
> If I comment out those lines in the whitelist it runs fine...
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/aheckmann/gleak/issues/3#issuecomment-2849493

## 

Aaron

**Comment by deremer** [comment]
v0.5.0-pre

**Comment by deremer** [comment]
If I console.log(process.version) right before the whitelist in gleak...that's what I get

**Comment by aheckmann** [comment]
can you try the release i just published (0.2.2)?

**Comment by deremer** [comment]
worked!

**Comment by deremer** [comment]
Damn this is a helpful tool. You rock dude.

**Comment by aheckmann** [comment]
Great!
